language: node_js
node_js:
 - "stable"
services: psql
cache:
  directories:
   - node_modules
before_script:
 - psql -c 'create database travis_ci' -U root
install:
 - yarn
 - yarn buildEnv
 - yarn sudo setup:rest-server
 - yarn sudo setup:socket-server
 - yarn sudo setup:services/coderunner-service
 - yarn sudo db:setup:rest-server
script:
 - yarn start
