language: node_js
node_js:
 - "stable"
services: postgresql
before_script:
 - createuser root
 - createdb codesling
 - psql -c 'create database travis_ci' -U postgres
 - yarn db:setup:rest-server
install:
 - yarn
 - yarn buildEnv
 - yarn setup:rest-server
 - yarn setup:socket-server
 - yarn setup:services/coderunner-service
script:
 - yarn start
