language: node_js
node_js:
 - "stable"
services: postgresql
before_script:
 - createuser root
 - createdb codesling
install:
 - yarn
 - yarn buildEnv
 - yarn setup:rest-server
 - yarn setup:socket-server
 - yarn setup:services/coderunner-service
 - yarn db:setup:rest-server
script:
 - yarn start
